-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."AuditTrails"
(
    "Id" uuid NOT NULL,
    "UserId" uuid,
    "TrailType" text COLLATE pg_catalog."default" NOT NULL,
    "DateUtc" timestamp with time zone NOT NULL,
    "EntityName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "PrimaryKey" character varying(100) COLLATE pg_catalog."default",
    "OldValues" text COLLATE pg_catalog."default" NOT NULL,
    "NewValues" text COLLATE pg_catalog."default" NOT NULL,
    "ChangedColumns" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_AuditTrails" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Departamento"
(
    "Id" character varying(4) COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "PaisId" character varying(2) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "CreatedBy" character varying(500) COLLATE pg_catalog."default" NOT NULL,
    "UpdatedBy" character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT "PK_Departamento" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Municipio"
(
    "Id" character varying(12) COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "DepartamentoId" character varying(4) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "CreatedBy" character varying(500) COLLATE pg_catalog."default" NOT NULL,
    "UpdatedBy" character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT "PK_Municipio" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Pais"
(
    "Id" character varying(2) COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "CreatedBy" character varying(500) COLLATE pg_catalog."default" NOT NULL,
    "UpdatedBy" character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT "PK_Pais" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Usuario"
(
    "Id" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Nombre" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Telefono" text COLLATE pg_catalog."default" NOT NULL,
    "Direccion_DireccionName" text COLLATE pg_catalog."default" NOT NULL,
    "Direccion_Municipioid" character varying(12) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "CreatedBy" character varying(500) COLLATE pg_catalog."default" NOT NULL,
    "UpdatedBy" character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT "PK_Usuario" PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS public."Departamento"
    ADD CONSTRAINT "FK_Departamento_Pais_PaisId" FOREIGN KEY ("PaisId")
    REFERENCES public."Pais" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Departamento_PaisId"
    ON public."Departamento"("PaisId");


ALTER TABLE IF EXISTS public."Municipio"
    ADD CONSTRAINT "FK_Municipio_Departamento_DepartamentoId" FOREIGN KEY ("DepartamentoId")
    REFERENCES public."Departamento" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Municipio_DepartamentoId"
    ON public."Municipio"("DepartamentoId");


ALTER TABLE IF EXISTS public."Usuario"
    ADD CONSTRAINT "FK_Usuario_Municipio_Direccion_Municipioid" FOREIGN KEY ("Direccion_Municipioid")
    REFERENCES public."Municipio" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Usuario_Direccion_Municipioid"
    ON public."Usuario"("Direccion_Municipioid");

END;